# Generated by Django 2.2.7 on 2019-12-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('isin', models.CharField(max_length=255)),
                ('code1', models.CharField(max_length=255)),
                ('code1_dummy', models.CharField(max_length=255)),
                ('nse_code', models.CharField(max_length=255)),
                ('nse_dummy', models.CharField(max_length=255)),
                ('dummy1', models.CharField(max_length=255)),
                ('dummy2', models.CharField(max_length=255)),
                ('market_cap', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
    ]
