# Generated by Django 2.2.4 on 2019-12-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekhigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.DateField()),
                ('security_name', models.CharField(max_length=255)),
                ('ltp', models.CharField(max_length=255)),
                ('week_high', models.CharField(max_length=255)),
                ('prev_week_high', models.CharField(max_length=255)),
                ('prev_week_high_date', models.CharField(max_length=255)),
                ('all_time_high', models.CharField(max_length=255)),
                ('all_time_high_date', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
            ],
        ),
    ]
