# Generated by Django 2.2.4 on 2019-12-29 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_weekhigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekhigh',
            name='high_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekhigh',
            name='security_code',
            field=models.CharField(max_length=255),
        ),
    ]
