# Generated by Django 2.2.7 on 2019-12-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_securitymaster_master_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitymaster',
            name='master_date',
        ),
    ]
