# Generated by Django 2.2.7 on 2019-12-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191230_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymaster',
            name='master_date',
            field=models.DateField(),
        ),
    ]
