# Generated by Django 2.2.7 on 2019-12-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191230_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitymaster',
            name='master_date',
        ),
    ]
