# Generated by Django 2.2.7 on 2020-01-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_securitymaster_master_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhavCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_date', models.DateField()),
                ('security_code', models.CharField(max_length=255)),
                ('security_group', models.CharField(max_length=255)),
                ('open', models.CharField(max_length=255)),
                ('high', models.CharField(max_length=255)),
                ('low', models.CharField(max_length=255)),
                ('close', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('prevclose', models.CharField(max_length=255)),
                ('no_trades', models.CharField(max_length=255)),
                ('no_of_shares', models.CharField(max_length=255)),
                ('net_turnover', models.CharField(max_length=255)),
                ('security_name', models.CharField(max_length=255)),
                ('isin_code', models.CharField(max_length=255)),
            ],
        ),
    ]
