# Generated by Django 2.2.7 on 2020-01-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bhavcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_date', models.DateField()),
                ('isin_code', models.CharField(max_length=255)),
                ('cp_latest_yesterday', models.BooleanField(null=True)),
                ('cp_latest_5d', models.BooleanField(null=True)),
                ('cp_latest_2w', models.BooleanField(null=True)),
                ('cp_latest_1m', models.BooleanField(null=True)),
                ('cp_latest_3m', models.BooleanField(null=True)),
                ('cp_latest_yesterday_pc', models.IntegerField(null=True)),
                ('cp_latest_5d_pc', models.IntegerField(null=True)),
                ('cp_latest_2w_pc', models.IntegerField(null=True)),
                ('cp_latest_1m_pc', models.IntegerField(null=True)),
                ('cp_latest_3m_pc', models.IntegerField(null=True)),
                ('vd_latest_yesterday', models.BooleanField(null=True)),
                ('vd_latest_5d', models.BooleanField(null=True)),
                ('vd_latest_2w', models.BooleanField(null=True)),
                ('vd_latest_1m', models.BooleanField(null=True)),
                ('vd_latest_3m', models.BooleanField(null=True)),
                ('vd_latest_yesterday_pc', models.IntegerField(null=True)),
                ('vd_latest_5d_pc', models.IntegerField(null=True)),
                ('vd_latest_2w_pc', models.IntegerField(null=True)),
                ('vd_latest_1m_pc', models.IntegerField(null=True)),
                ('vd_latest_3m_pc', models.IntegerField(null=True)),
                ('td_latest_yesterday', models.BooleanField(null=True)),
                ('td_latest_5d', models.BooleanField(null=True)),
                ('td_latest_2w', models.BooleanField(null=True)),
                ('td_latest_1m', models.BooleanField(null=True)),
                ('td_latest_3m', models.BooleanField(null=True)),
                ('td_latest_yesterday_pc', models.IntegerField(null=True)),
                ('td_latest_5d_pc', models.IntegerField(null=True)),
                ('td_latest_2w_pc', models.IntegerField(null=True)),
                ('td_latest_1m_pc', models.IntegerField(null=True)),
                ('td_latest_3m_pc', models.IntegerField(null=True)),
            ],
        ),
    ]
