from django.db import models


# Create your models here.
class SecurityMaster(models.Model):
    master_date = models.DateField()
    company_name = models.CharField(max_length=255)
    isin = models.CharField(max_length=255)
    code1 = models.CharField(max_length=255)
    code1_dummy = models.CharField(max_length=255)
    nse_code = models.CharField(max_length=255)
    nse_dummy = models.CharField(max_length=255)
    dummy1 = models.CharField(max_length=255)
    dummy2 = models.CharField(max_length=255)
    market_cap = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    sector = models.CharField(max_length=255)
    industry = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    currency = models.CharField(max_length=255)


class Weekhigh(models.Model):
    high_date = models.DateField()
    security_code = models.CharField(max_length=255)
    security_name = models.CharField(max_length=255)
    ltp = models.CharField(max_length=255)
    week_high = models.CharField(max_length=255)
    prev_week_high = models.CharField(max_length=255)
    prev_week_high_date = models.CharField(max_length=255)
    all_time_high = models.CharField(max_length=255)
    all_time_high_date = models.CharField(max_length=255)
    group = models.CharField(max_length=255)


class BhavCopy(models.Model):
    copy_date = models.DateField()
    security_code = models.CharField(max_length=255)
    security_name = models.CharField(max_length=255)
    security_group = models.CharField(max_length=255)
    open = models.CharField(max_length=255)
    high = models.CharField(max_length=255)
    low = models.CharField(max_length=255)
    close = models.CharField(max_length=255)
    last = models.CharField(max_length=255)
    prevclose = models.CharField(max_length=255)
    no_trades = models.CharField(max_length=255)
    no_of_shares = models.CharField(max_length=255)
    net_turnover = models.CharField(max_length=255)
    isin_code = models.CharField(max_length=255)


class Mapping(models.Model):
    mapping_date = models.DateField()
    isin_code = models.CharField(max_length=255)
    cp_latest_yesterday = models.BooleanField(null=True)
    cp_latest_5d = models.BooleanField(null=True)
    cp_latest_2w = models.BooleanField(null=True)
    cp_latest_1m = models.BooleanField(null=True)
    cp_latest_3m = models.BooleanField(null=True)
    cp_latest_yesterday_pc = models.IntegerField(null=True)
    cp_latest_5d_pc = models.IntegerField(null=True)
    cp_latest_2w_pc = models.IntegerField(null=True)
    cp_latest_1m_pc = models.IntegerField(null=True)
    cp_latest_3m_pc = models.IntegerField(null=True)
    vd_latest_yesterday = models.BooleanField(null=True)
    vd_latest_5d = models.BooleanField(null=True)
    vd_latest_2w = models.BooleanField(null=True)
    vd_latest_1m = models.BooleanField(null=True)
    vd_latest_3m = models.BooleanField(null=True)
    vd_latest_yesterday_pc = models.IntegerField(null=True)
    vd_latest_5d_pc = models.IntegerField(null=True)
    vd_latest_2w_pc = models.IntegerField(null=True)
    vd_latest_1m_pc = models.IntegerField(null=True)
    vd_latest_3m_pc = models.IntegerField(null=True)
    td_latest_yesterday = models.BooleanField(null=True)
    td_latest_5d = models.BooleanField(null=True)
    td_latest_2w = models.BooleanField(null=True)
    td_latest_1m = models.BooleanField(null=True)
    td_latest_3m = models.BooleanField(null=True)
    td_latest_yesterday_pc = models.IntegerField(null=True)
    td_latest_5d_pc = models.IntegerField(null=True)
    td_latest_2w_pc = models.IntegerField(null=True)
    td_latest_1m_pc = models.IntegerField(null=True)
    td_latest_3m_pc = models.IntegerField(null=True)
